# see https://github.com/devcontainers/ci/blob/main/docs/github-action.md
name: 'build' 
on:
  workflow_dispatch

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.2
        with:
          # Change this to point to your image name
          imageName: ghcr.io/stickmy/gather-devcontainer
          # imageTag: latest
          # Change this to be your CI task/script
          runCmd: |
            # Add multiple commands to run if needed
            make install-packages
            make ci-build